### ISSUE TITLE
Pushing to the Repo

### ISSUE THREAD

**Issue by PartialDevAdmin** [PartialDevAdmin/theme-changer#1]
@CDK2020 @Ralkage HELP!

```
remote: Permission to ReFlar/theme-changer.git denied to PartialDevAdmin.
fatal: unable to access 'https://github.com/ReFlar/theme-changer.git/': The requested URL returned error: 403
```

When I try to push to the repo :thinking:

**Comment by datitisev** [comment]
1) Please discuss this on the Discord
2) You must have your SSH keys messed up or be using HTTP auth wrong, as you have permission to push to the repo
![image](https://user-images.githubusercontent.com/6401250/40028963-dc6ee86c-57af-11e8-804d-05413b6a9ce6.png)

**Comment by PartialDevAdmin** [comment]
I don't have access to discord right now

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PartialDevAdmin** [comment]
@datitisev I am going to work on it from my end locally, and keep it on my user repo. Once done, I will transfer to Reflar
